export const actions = {
  profile: {
    DATA_FETCHING: "PROFILE_DATA_FETCHING",
    DATA_FETCHED: "PROFILE_DATA_FETCHED",
    DATA_FETCHED_ERROR: "PROFILE_DATA_FETCHED_ERROR",
    USER_DATA_EDITED: "USER_DATA_EDITED",
    IMAGE_UPDATED: "PROFILE_IMAGE_UPDATED",
  },
  blog: {
    BLOG_FETCHING: "BLOG_DATA_FETCHING",
    BLOG_FETCHED: "BLOG_DATA_FETCHED",
    BLOG_FETCHED_ERROR: "BLOG_DATA_FETCHED_ERROR",
    BLOG_DATA_EDITED: "BLOG_DATA_EDITED",
    IMAGE_UPDATED: "BLOG_IMAGE_UPDATED",
  },
};
